### ISSUE TITLE
Error when running server.js file

### ISSUE THREAD

**Issue by macappstudiocode** [ethand91/mediasoup-sample-server#1]
Hi team,

Got this issue.

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'mediasoup'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/cinibot/public_html/mediasoup-sample-server/src/worker.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by ethand91** [comment]
Please run npm i before starting the server.
